//
//  PerfomanceChartPresenter.swift
//  StockChart
//
//  Created by Dmitry Kuklin on 27/07/2020.
//  Copyright (c) 2020 DK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PerfomanceChartPresentationLogic {
    func presentStocks(response: PerfomanceChart.Stocks.Response)
    func presentError()
}

class PerfomanceChartPresenter: PerfomanceChartPresentationLogic {
    weak var viewController: PerfomanceChartDisplayLogic?

    // MARK: Do something

    func presentStocks(response: PerfomanceChart.Stocks.Response) {
        let viewModel = PerfomanceChart.Stocks.ViewModel(stocksPerfomance: response.stocksPerfomance)
        viewController?.displayStocks(viewModel: viewModel)
    }
    
    func presentError() {
        viewController?.displayError()
    }
}
