//
//  PerfomanceChartModels.swift
//  StockChart
//
//  Created by Dmitry Kuklin on 27/07/2020.
//  Copyright (c) 2020 DK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PerfomanceChart {
  // MARK: Use cases
  
    enum Stocks {
        
        struct Request{
        }

        struct Response {
            var stocksPerfomance: [StockPerformanceModel]
        }

        struct ViewModel {
            var stocksPerfomance: [StockPerformanceModel]
        }

    }
}
